project_id = "fcayyxezuevsredxzmdj"

[functions.enhance-prompt]
verify_jwt = true

[functions.generate-image]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.generate-newsletter-content]
verify_jwt = true

[functions.save-newsletter-draft]
verify_jwt = true

[functions.export-branded-pdf]
verify_jwt = true

[functions.search-real-images]
verify_jwt = false

[functions.generate-polished-image]
verify_jwt = false