import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { Resend } from "npm:resend@2.0.0";

const resend = new Resend(Deno.env.get("RESEND_API_KEY"));

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface LeadNotificationRequest {
  leadData: {
    name: string;
    email: string;
    phone?: string;
    type: string;
    source: string;
    message?: string;
  };
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { leadData }: LeadNotificationRequest = await req.json();
    
    console.log("Processing lead notification:", leadData);

    // Send notification email to the agent
    const emailResponse = await resend.emails.send({
      from: "Hyper-Local Pulse <leads@resend.dev>",
      to: ["your-email@example.com"], // Replace with agent's email
      subject: `New Lead: ${leadData.type} - ${leadData.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #F39C12;">🎯 New Lead Generated!</h2>
          
          <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="margin: 0 0 15px 0; color: #2C3E50;">Lead Information</h3>
            <p><strong>Name:</strong> ${leadData.name}</p>
            <p><strong>Email:</strong> ${leadData.email}</p>
            ${leadData.phone ? `<p><strong>Phone:</strong> ${leadData.phone}</p>` : ''}
            <p><strong>Lead Type:</strong> ${leadData.type}</p>
            <p><strong>Source:</strong> ${leadData.source}</p>
            ${leadData.message ? `
              <div style="margin-top: 15px;">
                <strong>Message:</strong>
                <p style="background: white; padding: 10px; border-radius: 4px; margin: 5px 0;">${leadData.message}</p>
              </div>
            ` : ''}
          </div>

          <div style="background: #e8f5e8; padding: 15px; border-radius: 8px; margin: 20px 0;">
            <h4 style="margin: 0 0 10px 0; color: #27ae60;">Next Steps:</h4>
            <ul style="margin: 0; padding-left: 20px;">
              <li>Follow up within 1 hour for best results</li>
              <li>Send personalized response based on lead type</li>
              <li>Add to your CRM system</li>
              <li>Schedule appropriate follow-up timeline</li>
            </ul>
          </div>

          <div style="text-align: center; margin: 30px 0;">
            <a href="https://your-app.com/analytics" 
               style="background: #F39C12; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
              View in Analytics Dashboard
            </a>
          </div>

          <p style="color: #666; font-size: 14px; text-align: center;">
            This lead was generated by your Hyper-Local Pulse marketing system.
          </p>
        </div>
      `,
    });

    console.log("Notification email sent successfully:", emailResponse);

    // Send welcome email to the lead
    let welcomeSubject = "";
    let welcomeMessage = "";
    
    switch (leadData.source) {
      case 'newsletter_signup':
        welcomeSubject = "Welcome to Our Market Updates";
        welcomeMessage = `
          <p>Thank you for subscribing to our weekly market updates!</p>
          <p>You'll receive valuable insights about your local real estate market, including:</p>
          <ul>
            <li>Weekly market trends and statistics</li>
            <li>New listings in your area</li>
            <li>Price changes and market insights</li>
            <li>Tips for buyers and sellers</li>
          </ul>
        `;
        break;
        
      case 'property_valuation':
        welcomeSubject = "Your Home Valuation Request Received";
        welcomeMessage = `
          <p>Thank you for requesting a home valuation!</p>
          <p>We've received your request and will provide you with a comprehensive market analysis within 24 hours.</p>
          <p>Your personalized report will include:</p>
          <ul>
            <li>Current market value estimate</li>
            <li>Recent comparable sales</li>
            <li>Market trends in your neighborhood</li>
            <li>Suggestions for maximizing your home's value</li>
          </ul>
        `;
        break;
        
      case 'consultation_request':
        welcomeSubject = "Consultation Request Confirmed";
        welcomeMessage = `
          <p>Thank you for requesting a consultation!</p>
          <p>We're excited to help you with your real estate goals. We'll contact you within 24 hours to schedule your free 30-minute strategy session.</p>
          <p>During our call, we'll discuss:</p>
          <ul>
            <li>Your specific real estate objectives</li>
            <li>Current market opportunities</li>
            <li>Customized strategy for your situation</li>
            <li>Next steps to achieve your goals</li>
          </ul>
        `;
        break;
        
      default:
        welcomeSubject = "Thank You for Your Interest";
        welcomeMessage = `
          <p>Thank you for your interest in our services!</p>
          <p>We've received your request and will be in touch soon with the information you requested.</p>
        `;
    }

    // Send welcome email to the lead
    const welcomeResponse = await resend.emails.send({
      from: "Hyper-Local Pulse <hello@resend.dev>",
      to: [leadData.email],
      subject: welcomeSubject,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #F39C12;">
            <h1 style="color: #2C3E50; margin: 0;">Hyper-Local Pulse</h1>
            <p style="color: #666; margin: 5px 0;">Your Local Real Estate Experts</p>
          </div>
          
          <div style="padding: 30px 20px;">
            <h2 style="color: #F39C12;">Hello ${leadData.name}!</h2>
            
            ${welcomeMessage}
            
            <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 25px 0;">
              <h3 style="margin: 0 0 15px 0; color: #2C3E50;">Stay Connected</h3>
              <p>Follow us for daily market insights and tips:</p>
              <p>📧 Email: hello@hyperlocalpulse.com</p>
              <p>📱 Phone: (555) 123-4567</p>
            </div>
            
            <p style="margin-top: 30px;">
              Best regards,<br>
              <strong>Your Hyper-Local Pulse Team</strong>
            </p>
          </div>
          
          <div style="background: #2C3E50; color: white; padding: 20px; text-align: center;">
            <p style="margin: 0; font-size: 14px;">
              © 2024 Hyper-Local Pulse. All rights reserved.
            </p>
          </div>
        </div>
      `,
    });

    console.log("Welcome email sent successfully:", welcomeResponse);

    return new Response(
      JSON.stringify({ 
        success: true, 
        notificationSent: emailResponse.id,
        welcomeSent: welcomeResponse.id
      }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          ...corsHeaders,
        },
      }
    );
    
  } catch (error: any) {
    console.error("Error in send-lead-notification function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);