// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcayyxezuevsredxzmdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjYXl5eGV6dWV2c3JlZHh6bWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODI0ODcsImV4cCI6MjA3MDQ1ODQ4N30.km3p0FytDZqPHnBEEPpj-xsIdneseNg8lNyRBHpBKFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});